# -*- coding: utf-8 -*-
"""yolo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ABRACMhKIO_qSYaafmKxsTTdkzAW8Ht
"""

pip list

import os
os.chdir('/content/drive/My Drive/RPC')

!ls

from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()

trainer.setDataDirectory(data_directory="/content/drive/My Drive/RPC")
trainer.setTrainConfig(object_names_array=["puffed_food","dried_fruit","dried_food","instant_drink","instant_noodles","dessert","drink","alcohol","milk","canned_food","chocolate","gum","candy","seasoner","personal_hygiene","tissue","stationery"], batch_size=4, num_experiments=200, train_from_pretrained_model="/content/drive/My Drive/RPC/pretrained-yolov3.h5")
trainer.trainModel()



import os
os.chdir('/content/drive/My Drive/RPC/train')

!ls

import cv2
import numpy as np

cap = cv2.VideoCapture('video-clip.mp4')

import os
os.chdir('/content')

from google.colab.patches import cv2_imshow

frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
out = cv2.VideoWriter('outpy.mp4',cv2.VideoWriter_fourcc('M','J','P','G'), 10, (frame_width,frame_height))
while(True):
  ret, frame = cap.read()
  if ret == True: 
    print(frame)
    out.write(frame)
    cv2_imshow(frame)
    if cv2.waitKey(1) == 27:
      break
  else:
    break
cap.release()
cv2.destroyAllWindows()

import os
os.chdir('/content/drive/My Drive')

!unzip repaired.zip

